// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakip.Models;

#nullable disable

namespace StokTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328000705_AddCihazKisiBilgileri")]
    partial class AddCihazKisiBilgileri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("StokTakip.Models.Cihaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlinanKisiAdSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlinanKisiTelefon")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlisMaliyeti")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkaModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<string>("SatilanKisiAdSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("SatilanKisiTelefon")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SatisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriNo")
                        .IsUnique();

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("StokTakip.Models.CihazHarcama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<int>("CihazId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HarcamaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("UrunId");

                    b.ToTable("CihazHarcamalar");
                });

            modelBuilder.Entity("StokTakip.Models.CihazYapilacak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CihazId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CihazId", "Sira")
                        .IsUnique();

                    b.ToTable("CihazYapilacaklar");
                });

            modelBuilder.Entity("StokTakip.Models.Gider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GiderTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Giderler");
                });

            modelBuilder.Entity("StokTakip.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("StokTakip.Models.PilLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HucreModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrtalamaIcDirenc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrtalamaKapasite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LotNo")
                        .IsUnique();

                    b.ToTable("PilLotlari");
                });

            modelBuilder.Entity("StokTakip.Models.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Indirim")
                        .HasColumnType("TEXT");

                    b.Property<string>("KargoTakipNo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KargoUcreti")
                        .HasColumnType("TEXT");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("StokTakip.Models.SatisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SatisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SatisDetaylari");
                });

            modelBuilder.Entity("StokTakip.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OncekiStok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SonrakiStok")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("StokTakip.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinStok")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SeriNoTakip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barkod")
                        .IsUnique();

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("StokTakip.Models.CihazHarcama", b =>
                {
                    b.HasOne("StokTakip.Models.Cihaz", "Cihaz")
                        .WithMany("Harcamalar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakip.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");

                    b.Navigation("Cihaz");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokTakip.Models.CihazYapilacak", b =>
                {
                    b.HasOne("StokTakip.Models.Cihaz", "Cihaz")
                        .WithMany("Yapilacaklar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("StokTakip.Models.Satis", b =>
                {
                    b.HasOne("StokTakip.Models.Musteri", "Musteri")
                        .WithMany("Satislar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("StokTakip.Models.SatisDetay", b =>
                {
                    b.HasOne("StokTakip.Models.Satis", "Satis")
                        .WithMany("Detaylar")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakip.Models.Urun", "Urun")
                        .WithMany("SatisDetaylari")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokTakip.Models.StokHareket", b =>
                {
                    b.HasOne("StokTakip.Models.Urun", "Urun")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokTakip.Models.Cihaz", b =>
                {
                    b.Navigation("Harcamalar");

                    b.Navigation("Yapilacaklar");
                });

            modelBuilder.Entity("StokTakip.Models.Musteri", b =>
                {
                    b.Navigation("Satislar");
                });

            modelBuilder.Entity("StokTakip.Models.Satis", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("StokTakip.Models.Urun", b =>
                {
                    b.Navigation("SatisDetaylari");

                    b.Navigation("StokHareketleri");
                });
#pragma warning restore 612, 618
        }
    }
}
